openapi: 3.1.0
info:
  title: Scoring
  version: 2.0.1
  description: 'Retrieve contact scoring data. Use this API to get scores for all contacts in

    your account, scores modified since a given date, the score for a specific

    contact by ID or email, and scores for contacts within a specific address book

    or segment.'
x-readme:
  headers: []
  explorer-enabled: true
  proxy-enabled: true
x-readme-fauxas: true
x-samples-languages:
- curl
- csharp
- java
- javascript
- node
- python
- php
- ruby
externalDocs:
  description: Learn more about Dotdigital APIs
  url: https://developer.dotdigital.com
servers:
- url: https://{region}-api.dotdigital.com
  variables:
    region:
      default: r1
      enum:
      - r1
      - r2
      - r3
      description: The Dotdigital region id your account belongs to
security:
- basicAuth: []
paths:
  /v2/contacts/score:
    parameters:
    - in: header
      name: x-ddg-integration-token
      required: false
      description: If you are a partner of Dotdigital and have a [verified integration](https://developer.dotdigital.com/docs/partner-integration-verification) then include your [integration tracking token](https://developer.dotdigital.co/docs/verified-integration-tracking) here.
      schema:
        type: string
        pattern: /^(?:\{{0,1}(?:[0-9a-fA-F]){8}-(?:[0-9a-fA-F]){4}-(?:[0-9a-fA-F]){4}-(?:[0-9a-fA-F]){4}-(?:[0-9a-fA-F]){12}\}{0,1})$/
        example: 5a96bc79-19a7-4544-973b-e2da0c9136f9
    get:
      summary: Get scoring for contacts
      deprecated: false
      description: Gets contact scoring for all contacts in the account
      operationId: get-scoring-for-contacts
      tags:
      - Scoring
      parameters:
      - name: select
        in: query
        description: The number of records to select between 1 and 1000 to retrieve.
        required: false
        schema:
          type: integer
          format: int32
          minimum: 1
          maximum: 1000
          default: 1000
      - name: skip
        in: query
        description: The numbers of records to skip in the result set.
        required: false
        schema:
          type: integer
          minimum: 1
          format: int32
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                  - contactId
                  - email
                  - dateModified
                  - score
                  - scoreLabel
                  - suitability
                  properties:
                    contactId:
                      description: The contacts unique id the score relates to.
                      type: integer
                      default: 0
                      examples:
                      - 1
                    email:
                      description: The email address of the contact the score relates to.
                      type: string
                      format: email
                      examples:
                      - sara.holst@example.com
                    dateModified:
                      description: The date and time in UTC ISO 8601 format the record was modified.
                      type: string
                      format: date-time
                      examples:
                      - '2020-01-01 09:40:18.527000+00:00'
                    scoreLabel:
                      description: The scores label.
                      type: string
                      examples:
                      - Cool
                    score:
                      description: The score.
                      type: integer
                      default: 0
                      examples:
                      - 20
                    engagement:
                      description: The engagement score / level of interest.
                      type: integer
                      default: 0
                      examples:
                      - 10
                    suitability:
                      description: The suitability score.
                      type: integer
                      default: 0
                      examples:
                      - 30
              examples:
                Result:
                  summary: Result
                  value:
                  - contactId: 1
                    email: sara.holst@example.com
                    dateModified: '2020-01-01 09:40:18.527000+00:00'
                    scoreLabel: Cool
                    score: 20
                    engagement: 10
                    suitability: 30
                  - contactId: 2
                    email: tiffany.valverde@example.com
                    dateModified: '2020-01-01 09:40:18.527000+00:00'
                    scoreLabel: Cold
                    score: 2
                    engagement: 1
                    suitability: 3
  /v2/contacts/score/modified-since/{date}:
    parameters:
    - in: header
      name: x-ddg-integration-token
      required: false
      description: If you are a partner of Dotdigital and have a [verified integration](https://developer.dotdigital.com/docs/partner-integration-verification) then include your [integration tracking token](https://developer.dotdigital.co/docs/verified-integration-tracking) here.
      schema:
        type: string
        pattern: /^(?:\{{0,1}(?:[0-9a-fA-F]){8}-(?:[0-9a-fA-F]){4}-(?:[0-9a-fA-F]){4}-(?:[0-9a-fA-F]){4}-(?:[0-9a-fA-F]){12}\}{0,1})$/
        example: 5a96bc79-19a7-4544-973b-e2da0c9136f9
    get:
      summary: Get scoring modified since date for contacts
      deprecated: false
      description: Gets contacts whose contact scoring data has been modified since a given UTC date-time.
      operationId: get-scoring-modified-since-date-for-contacts
      tags:
      - Scoring
      parameters:
      - name: date
        in: path
        description: The date from which any modified contact scoring data will be returned as UTC time in [ISO 8601 format](https://www.w3.org/TR/xmlschema-2/#dateTime)
        required: true
        example: '2026-01-01T00:00:00.000Z'
        schema:
          type: string
          format: date-time
      - name: select
        in: query
        description: The number of records to select between 1 and 1000 to retrieve.
        required: false
        schema:
          type: integer
          format: int32
          minimum: 1
          maximum: 1000
          default: 1000
      - name: skip
        in: query
        description: The numbers of records to skip in the result set.
        required: false
        schema:
          type: integer
          minimum: 1
          format: int32
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                  - contactId
                  - email
                  - dateModified
                  - score
                  - scoreLabel
                  - suitability
                  properties:
                    contactId:
                      description: The contacts unique id the score relates to.
                      type: integer
                      default: 0
                      examples:
                      - 1
                    email:
                      description: The email address of the contact the score relates to.
                      type: string
                      format: email
                      examples:
                      - sara.holst@example.com
                    dateModified:
                      description: The date and time in UTC ISO 8601 format the record was modified.
                      type: string
                      format: date-time
                      examples:
                      - '2020-01-01 09:40:18.527000+00:00'
                    scoreLabel:
                      description: The scores label.
                      type: string
                      examples:
                      - Cool
                    score:
                      description: The score.
                      type: integer
                      default: 0
                      examples:
                      - 20
                    engagement:
                      description: The engagement score / level of interest.
                      type: integer
                      default: 0
                      examples:
                      - 10
                    suitability:
                      description: The suitability score.
                      type: integer
                      default: 0
                      examples:
                      - 30
              examples:
                Result:
                  summary: Result
                  value:
                  - contactId: 1
                    email: sara.holst@example.com
                    dateModified: '2020-01-01 09:40:18.527000+00:00'
                    scoreLabel: Cool
                    score: 20
                    engagement: 10
                    suitability: 30
                  - contactId: 2
                    email: tiffany.valverde@example.com
                    dateModified: '2020-01-01 09:40:18.527000+00:00'
                    scoreLabel: Cold
                    score: 2
                    engagement: 1
                    suitability: 3
  /v2/contacts/{contactIdentifier}/score:
    parameters:
    - in: header
      name: x-ddg-integration-token
      required: false
      description: If you are a partner of Dotdigital and have a [verified integration](https://developer.dotdigital.com/docs/partner-integration-verification) then include your [integration tracking token](https://developer.dotdigital.co/docs/verified-integration-tracking) here.
      schema:
        type: string
        pattern: /^(?:\{{0,1}(?:[0-9a-fA-F]){8}-(?:[0-9a-fA-F]){4}-(?:[0-9a-fA-F]){4}-(?:[0-9a-fA-F]){4}-(?:[0-9a-fA-F]){12}\}{0,1})$/
        example: 5a96bc79-19a7-4544-973b-e2da0c9136f9
    get:
      summary: Get scoring for contact
      deprecated: false
      description: Gets contact scoring for a contact
      operationId: get-scoring-for-contact-by-email
      tags:
      - Scoring
      parameters:
      - name: contactIdentifier
        in: path
        description: Either the contact id or email address of the contact
        required: true
        example: bob@example.com
        schema:
          oneOf:
          - description: Email address
            type: string
            format: email
          - description: Contact ID
            type: integer
            minimum: 0
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                type: object
                required:
                - contactId
                - email
                - dateModified
                - score
                - scoreLabel
                - suitability
                properties:
                  contactId:
                    description: The contacts unique id the score relates to.
                    type: integer
                    default: 0
                    examples:
                    - 1
                  email:
                    description: The email address of the contact the score relates to.
                    type: string
                    format: email
                    examples:
                    - sara.holst@example.com
                  dateModified:
                    description: The date and time in UTC ISO 8601 format the record was modified.
                    type: string
                    format: date-time
                    examples:
                    - '2020-01-01 09:40:18.527000+00:00'
                  scoreLabel:
                    description: The scores label.
                    type: string
                    examples:
                    - Cool
                  score:
                    description: The score.
                    type: integer
                    default: 0
                    examples:
                    - 20
                  engagement:
                    description: The engagement score / level of interest.
                    type: integer
                    default: 0
                    examples:
                    - 10
                  suitability:
                    description: The suitability score.
                    type: integer
                    default: 0
                    examples:
                    - 30
              examples:
                Result:
                  summary: Result
                  value:
                    contactId: 3
                    email: nelson.redeker@example.com
                    dateModified: '2020-01-01 09:40:18.527000+00:00'
                    scoreLabel: Hot
                    score: 80
                    engagement: 70
                    suitability: 90
  /v2/address-books/{id}/contacts/score:
    parameters:
    - in: header
      name: x-ddg-integration-token
      required: false
      description: If you are a partner of Dotdigital and have a [verified integration](https://developer.dotdigital.com/docs/partner-integration-verification) then include your [integration tracking token](https://developer.dotdigital.co/docs/verified-integration-tracking) here.
      schema:
        type: string
        pattern: /^(?:\{{0,1}(?:[0-9a-fA-F]){8}-(?:[0-9a-fA-F]){4}-(?:[0-9a-fA-F]){4}-(?:[0-9a-fA-F]){4}-(?:[0-9a-fA-F]){12}\}{0,1})$/
        example: 5a96bc79-19a7-4544-973b-e2da0c9136f9
    get:
      summary: Get scoring for contacts in address book
      deprecated: false
      description: Gets contact scoring for contacts within a specific address book or segment
      operationId: get-scoring-for-contacts-in-address-book
      tags:
      - Scoring
      parameters:
      - name: id
        in: path
        description: The id of the address book
        required: true
        example: 0
        schema:
          type: integer
          format: int32
          minimum: 0
      - name: select
        in: query
        description: The number of records to select between 1 and 1000 to retrieve.
        required: false
        schema:
          type: integer
          format: int32
          minimum: 1
          maximum: 1000
          default: 1000
      - name: skip
        in: query
        description: The numbers of records to skip in the result set.
        required: false
        schema:
          type: integer
          minimum: 1
          format: int32
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                  - contactId
                  - email
                  - dateModified
                  - score
                  - scoreLabel
                  - suitability
                  properties:
                    contactId:
                      description: The contacts unique id the score relates to.
                      type: integer
                      default: 0
                      examples:
                      - 1
                    email:
                      description: The email address of the contact the score relates to.
                      type: string
                      format: email
                      examples:
                      - sara.holst@example.com
                    dateModified:
                      description: The date and time in UTC ISO 8601 format the record was modified.
                      type: string
                      format: date-time
                      examples:
                      - '2020-01-01 09:40:18.527000+00:00'
                    scoreLabel:
                      description: The scores label.
                      type: string
                      examples:
                      - Cool
                    score:
                      description: The score.
                      type: integer
                      default: 0
                      examples:
                      - 20
                    engagement:
                      description: The engagement score / level of interest.
                      type: integer
                      default: 0
                      examples:
                      - 10
                    suitability:
                      description: The suitability score.
                      type: integer
                      default: 0
                      examples:
                      - 30
              examples:
                Result:
                  summary: Result
                  value:
                  - contactId: 1
                    email: sara.holst@example.com
                    dateModified: '2020-01-01 09:40:18.527000+00:00'
                    scoreLabel: Cool
                    score: 20
                    engagement: 10
                    suitability: 30
                  - contactId: 2
                    email: tiffany.valverde@example.com
                    dateModified: '2020-01-01 09:40:18.527000+00:00'
                    scoreLabel: Cold
                    score: 2
                    engagement: 1
                    suitability: 3
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  schemas:
    scoreInstance:
      type: object
      required:
      - contactId
      - email
      - dateModified
      - score
      - scoreLabel
      - suitability
      properties:
        contactId:
          description: The contacts unique id the score relates to.
          type: integer
          default: 0
          examples:
          - 1
        email:
          description: The email address of the contact the score relates to.
          type: string
          format: email
          examples:
          - sara.holst@example.com
        dateModified:
          description: The date and time in UTC ISO 8601 format the record was modified.
          type: string
          format: date-time
          examples:
          - '2020-01-01 09:40:18.527000+00:00'
        scoreLabel:
          description: The scores label.
          type: string
          examples:
          - Cool
        score:
          description: The score.
          type: integer
          default: 0
          examples:
          - 20
        engagement:
          description: The engagement score / level of interest.
          type: integer
          default: 0
          examples:
          - 10
        suitability:
          description: The suitability score.
          type: integer
          default: 0
          examples:
          - 30
